baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Slick Savers"
[params]
prism_syntax_highlighting = true
  [params.prism]
    languages = [
      "markup",
      "css",
      "clike",
      "javascript"
    ]
    plugins = [
      "normalize-whitespace",
      "toolbar",
      "copy-to-clipboard"
    ]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS"]
disableAdsense = false
[taxonomies]
   tag = "tags"
   category = "category"
